//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Capa_Entidad;
    
    
    public partial class Bolsa_de_EmpleadosEntities : DbContext
    {
        public Bolsa_de_EmpleadosEntities()
            : base("name=Bolsa_de_EmpleadosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTRADOR> ADMINISTRADORs { get; set; }
        public virtual DbSet<CATEGORIA> CATEGORIAS { get; set; }
        public virtual DbSet<DATOS_VACANTE> DATOS_VACANTE { get; set; }
        public virtual DbSet<NUMERO_DE_PAGINACION> NUMERO_DE_PAGINACION { get; set; }
        public virtual DbSet<POSTER> POSTERs { get; set; }
    }
}
